"""create jobs table

Revision ID: 487c139232b3
Revises: 
Create Date: 2026-09-21 12:25:50.817700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487c139232b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('seniority', sa.String(length=16), nullable=True),
    sa.Column('required_skills', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('min_years', sa.Integer(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('remote', sa.String(length=16), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('blockers', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("remote IS NULL OR remote IN ('onsite', 'hybrid', 'remote', 'unknown')", name='ck_jobs_remote'),
    sa.CheckConstraint("seniority IS NULL OR seniority IN ('junior', 'mid', 'senior', 'lead', 'unknown')", name='ck_jobs_seniority'),
    sa.CheckConstraint("status IN ('pending', 'fetching', 'scoring', 'scored', 'extraction_failed', 'fetch_failed')", name='ck_jobs_status'),
    sa.CheckConstraint('fit_score IS NULL OR (fit_score >= 0 AND fit_score <= 100)', name='ck_jobs_fit_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_content_hash'), 'jobs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_content_hash'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
