"""add scored_by to jobs

Revision ID: 90644ad9d800
Revises: 4dab290d4699
Create Date: 2026-09-21 12:55:03.360843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90644ad9d800'
down_revision: Union[str, Sequence[str], None] = '4dab290d4699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('scored_by', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'scored_by')
    # ### end Alembic commands ###
