"""create profiles table

Revision ID: ab921fa1b129
Revises: 04c5a9349940
Create Date: 2026-09-21 12:40:20.214784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab921fa1b129'
down_revision: Union[str, Sequence[str], None] = '04c5a9349940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cv_text', sa.Text(), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('target_roles', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('locations', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('years_experience >= 0 AND years_experience <= 70', name='ck_profiles_years_experience'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
